global using CrimeWatch.Application.Specifications;
global using CrimeWatch.Domain.Enums;
global using CrimeWatch.Domain.ValueObjects;
global using CrimeWatch.Infrastructure.Contracts.Repositories;
global using FluentValidation;
global using MediatR;
global using CrimeWatch.Application.Enums;
global using CrimeWatch.Application.Common;
global using Microsoft.AspNetCore.Http;
